interface PlanResult {
  overview?: string;
  difficulty?: string;
  totalDistance?: number;
  totalElevation?: number;
  bestSeason?: string;
  days?: { day: number; title: string; description: string; distance: number; elevation: number; highlights: string }[];
  gearList?: string[];
  safetyTips?: string[];
}

export function downloadWordDoc(
  result: PlanResult,
  destination: string,
  days: number,
  fitness: string,
  language: 'zh' | 'en'
) {
  const isZh = language === 'zh';
  const t = (zh: string, en: string) => isZh ? zh : en;

  const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta charset="utf-8"><title>${destination}</title>
<style>
  body { font-family: 'Microsoft YaHei', 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; color: #1a1a1a; line-height: 1.8; }
  h1 { font-size: 24px; border-bottom: 3px solid #e85d04; padding-bottom: 12px; margin-bottom: 24px; }
  h2 { font-size: 18px; color: #e85d04; margin-top: 28px; border-left: 4px solid #e85d04; padding-left: 10px; }
  h3 { font-size: 15px; color: #333; margin-top: 18px; }
  p { font-size: 13px; margin: 8px 0; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; font-size: 13px; }
  th { background: #f5f5f5; font-weight: 600; }
  ul { padding-left: 20px; }
  li { font-size: 13px; margin: 4px 0; }
  .stats { background: #f8f8f8; padding: 12px 16px; border-radius: 6px; margin: 12px 0; font-size: 13px; }
  .day-block { margin: 16px 0; padding: 12px 16px; border-left: 3px solid #e85d04; background: #fafafa; }
  .day-block h3 { margin-top: 0; }
  .day-detail { font-size: 12px; color: #666; margin-top: 6px; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #999; }
  .checklist li { list-style: none; }
  .checklist li::before { content: '☐ '; }
  .safety li { list-style: none; }
  .safety li::before { content: '⚠ '; }
</style></head><body>
<h1>🥾 ${destination}</h1>
${result.overview ? `<p>${result.overview}</p>` : ''}

<h2>${t('路线数据', 'Trail Stats')}</h2>
<table>
${result.difficulty ? `<tr><th>${t('难度', 'Difficulty')}</th><td>${result.difficulty}</td></tr>` : ''}
${result.totalDistance ? `<tr><th>${t('总距离', 'Total Distance')}</th><td>${result.totalDistance} km</td></tr>` : ''}
${result.totalElevation ? `<tr><th>${t('累计爬升', 'Total Elevation')}</th><td>+${result.totalElevation}m</td></tr>` : ''}
<tr><th>${t('天数', 'Days')}</th><td>${days}</td></tr>
<tr><th>${t('体能要求', 'Fitness')}</th><td>${fitness}</td></tr>
${result.bestSeason ? `<tr><th>${t('最佳季节', 'Best Season')}</th><td>${result.bestSeason}</td></tr>` : ''}
</table>

${result.days && result.days.length > 0 ? `
<h2>${t('每日行程', 'Daily Itinerary')}</h2>
${result.days.map(d => `
<div class="day-block">
  <h3>${t('第', 'Day')} ${d.day}${t('天', '')}: ${d.title}</h3>
  <p>${d.description}</p>
  <div class="day-detail">
    ${d.distance ? `${t('距离', 'Distance')}: ${d.distance} km · ` : ''}
    ${d.elevation ? `${t('爬升', 'Elevation')}: +${d.elevation}m · ` : ''}
    ${d.highlights ? `${t('亮点', 'Highlights')}: ${d.highlights}` : ''}
  </div>
</div>
`).join('')}
` : ''}

${result.gearList && result.gearList.length > 0 ? `
<h2>${t('装备清单', 'Gear Checklist')}</h2>
<ul class="checklist">
${result.gearList.map(item => `<li>${item}</li>`).join('\n')}
</ul>
` : ''}

${result.safetyTips && result.safetyTips.length > 0 ? `
<h2>${t('安全提示', 'Safety Tips')}</h2>
<ul class="safety">
${result.safetyTips.map(tip => `<li>${tip}</li>`).join('\n')}
</ul>
` : ''}

<div class="footer">
  <p>${t('由 KinTrail 生成', 'Generated by KinTrail')} · ${new Date().toISOString().slice(0, 10)}</p>
  <p>https://frontend-xi-tan-11.vercel.app</p>
</div>
</body></html>`;

  const blob = new Blob(['\ufeff' + html], { type: 'application/msword;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const slug = destination.replace(/[^a-zA-Z0-9\u4e00-\u9fff]/g, '_').slice(0, 30);
  a.download = `${slug}_${isZh ? '徒步攻略' : 'hiking_plan'}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export interface TrailGuideDownload {
  title: string;
  overview?: string;
  stats: {
    difficulty?: string;
    distance?: number;
    elevationGain?: number;
    duration?: number;
    season?: string;
    region?: string;
    country?: string;
  };
  days?: { dayNumber: number; title: string; description?: string; distance?: number; elevation?: number; highlights?: string }[];
  sections: { title: string; items: string[] }[];
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export function downloadTrailGuideDoc(guide: TrailGuideDownload, language: 'zh' | 'en') {
  const isZh = language === 'zh';
  const t = (zh: string, en: string) => isZh ? zh : en;

  const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta charset="utf-8"><title>${escapeHtml(guide.title)}</title>
<style>
  body { font-family: 'Microsoft YaHei', 'Segoe UI', sans-serif; max-width: 820px; margin: 40px auto; color: #1a1a1a; line-height: 1.75; }
  h1 { font-size: 25px; border-bottom: 3px solid #e85d04; padding-bottom: 12px; margin-bottom: 22px; }
  h2 { font-size: 18px; color: #e85d04; margin-top: 28px; border-left: 4px solid #e85d04; padding-left: 10px; }
  h3 { font-size: 15px; margin: 16px 0 6px; }
  p, li, td, th { font-size: 13px; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
  th { background: #f5f5f5; font-weight: 600; width: 28%; }
  ul { padding-left: 20px; }
  .day-block { margin: 14px 0; padding: 12px 16px; border-left: 3px solid #e85d04; background: #fafafa; }
  .muted { color: #666; font-size: 12px; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #999; }
</style></head><body>
<h1>${escapeHtml(guide.title)}</h1>
${guide.overview ? `<p>${escapeHtml(guide.overview)}</p>` : ''}

<h2>${t('路线数据', 'Trail Stats')}</h2>
<table>
${guide.stats.difficulty ? `<tr><th>${t('难度', 'Difficulty')}</th><td>${escapeHtml(guide.stats.difficulty)}</td></tr>` : ''}
${guide.stats.distance ? `<tr><th>${t('距离', 'Distance')}</th><td>${guide.stats.distance} km</td></tr>` : ''}
${guide.stats.elevationGain ? `<tr><th>${t('累计爬升', 'Elevation Gain')}</th><td>+${guide.stats.elevationGain}m</td></tr>` : ''}
${guide.stats.duration ? `<tr><th>${t('建议天数', 'Suggested Duration')}</th><td>${guide.stats.duration}${t('天', ' days')}</td></tr>` : ''}
${guide.stats.season ? `<tr><th>${t('季节', 'Season')}</th><td>${escapeHtml(guide.stats.season)}</td></tr>` : ''}
${guide.stats.region || guide.stats.country ? `<tr><th>${t('区域', 'Region')}</th><td>${escapeHtml([guide.stats.region, guide.stats.country].filter(Boolean).join(', '))}</td></tr>` : ''}
</table>

${guide.sections.map(section => `
<h2>${escapeHtml(section.title)}</h2>
<ul>
${section.items.map(item => `<li>${escapeHtml(item)}</li>`).join('\n')}
</ul>
`).join('\n')}

${guide.days && guide.days.length > 0 ? `
<h2>${t('每日行程', 'Daily Itinerary')}</h2>
${guide.days.map(day => `
<div class="day-block">
  <h3>${t('第', 'Day ')}${day.dayNumber}${t('天', '')}: ${escapeHtml(day.title)}</h3>
  ${day.description ? `<p>${escapeHtml(day.description)}</p>` : ''}
  <p class="muted">
    ${day.distance ? `${t('距离', 'Distance')}: ${day.distance} km · ` : ''}
    ${day.elevation ? `${t('爬升', 'Elevation')}: +${day.elevation}m · ` : ''}
    ${day.highlights ? `${t('亮点', 'Highlights')}: ${escapeHtml(day.highlights)}` : ''}
  </p>
</div>
`).join('')}
` : ''}

<div class="footer">
  <p>${t('由 KinTrail 生成。出行前请核对官方公告、天气、交通和当地管制。', 'Generated by KinTrail. Verify official notices, weather, transport, and local restrictions before departure.')} · ${new Date().toISOString().slice(0, 10)}</p>
</div>
</body></html>`;

  const blob = new Blob(['\ufeff' + html], { type: 'application/msword;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const slug = guide.title.replace(/[^a-zA-Z0-9\u4e00-\u9fff]/g, '_').slice(0, 30);
  a.download = `${slug}_${isZh ? '路线攻略' : 'trail_guide'}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
