services:
  - type: web
    name: hiking-api
    env: node
    region: singapore
    buildCommand: npm install && npx prisma generate && npm run build && npx prisma db push
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hiking-db
          property: connectionString

databases:
  - name: hiking-db
    plan: free
